// Stage the Cloudflare Worker deploy bundle for the CGA research exhibit.
// Copies the landing page + pre-rendered demo/eval JSON + architecture doc
// into deploy/public/. Run: node deploy/build.cjs (verifies references).
// demo.json and eval.json are generated by scripts/capture.mjs (recorded runs).
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const pub = path.join(__dirname, "public");

function copy(srcRel, destRel) {
  const src = path.join(root, srcRel);
  const dest = path.join(pub, destRel);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(src, dest);
}

fs.rmSync(pub, { recursive: true, force: true });
copy("index.html", "index.html");
copy("ARCHITECTURE.md", "ARCHITECTURE.md");
copy("RESEARCH-REPORT.md", "RESEARCH-REPORT.md");
copy("public-exhibit/demo.json", "demo.json");
copy("public-exhibit/eval.json", "eval.json");

// Guard: every local asset reference inside the bundle must resolve,
// and every /api/* reference must be implemented by worker.js.
(function verifyBundle() {
  const files = [];
  (function walk(dir) {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else if (/\.(js|html)$/.test(e.name)) files.push(p);
    }
  })(pub);
  const missing = [];
  const apiRefs = new Set();
  for (const f of files) {
    const text = fs.readFileSync(f, "utf8");
    for (const m of text.matchAll(/(?:href|src)="(\/[^"]+)"/g)) {
      if (m[1].startsWith("/api/")) { apiRefs.add(m[1]); continue; }
      const target = path.join(pub, decodeURIComponent(m[1]).replace(/^[/\\]+/, ""));
      if (!fs.existsSync(target)) missing.push(`${path.relative(pub, f)} -> ${m[1]}`);
    }
  }
  const workerSrc = fs.readFileSync(path.join(__dirname, "worker.js"), "utf8");
  for (const ref of apiRefs) {
    if (!workerSrc.includes(`"${ref}"`) && !workerSrc.includes(`'${ref}'`)) {
      missing.push(`worker.js does not implement ${ref}`);
    }
  }
  if (missing.length > 0) {
    console.error("deploy bundle has unresolvable references:\n" + missing.join("\n"));
    process.exit(1);
  }
  console.log(`bundle check: ${files.length} files scanned, all references resolve.`);
})();

console.log("research exhibit bundle staged in deploy/public.");
